name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - name: Install dependencies
        run: npm ci
        if: github.repository != 'ThinkStackLimited/iac-template'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        if: env.GITHUB_TOKEN != '' && github.repository != 'ThinkStackLimited/iac-template'
